# cliamp theme template for Omarchy
# Project: oldjobobo-custom-omarchy-templates
# Template: cliamp.toml.tpl
# Generated by: Omarchy template substitution
# Source: colors.toml
#
# Renders to: ~/.config/omarchy/current/theme/cliamp.toml
# Deployed by: ~/.config/omarchy/hooks/theme-set.d/50-cliamp.sh
#
# Color mapping:
#   accent    <- accent   — interactive highlight color
#   bright_fg <- color15  — primary text / time display
#   fg        <- color7   — secondary/muted text / help bar
#   green     <- color2   — playing indicator / volume bar / spectrum low
#   yellow    <- color3   — spectrum mid frequencies
#   red       <- color1   — spectrum high / errors

accent    = "#{{ accent }}"
bright_fg = "#{{ color15 }}"
fg        = "#{{ color7 }}"
green     = "#{{ color2 }}"
yellow    = "#{{ color3 }}"
red       = "#{{ color1 }}"
